JudrieActivity/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from ownlist import views 
from django.urls import path  

urlpatterns = [    
    url(r'^$', views.home_page, name='home_page'),    
    url(r'^new$', views.new_list, name='new_list'),   
    url(r'^(\d+)/next$', views.view_list, name='view_list'),  
    url('admin/', admin.site.urls),    
    url(r'^(\d+)/add_item$', views.add_item, name='add_item'),

    url(r'^edit/(?P<id>\d+)$', views.edit, name='edit'),
    url(r'^edit/update/(?P<id>\d+)$', views.update, name='update'),
    url(r'^delete/(?P<id>\d+)$', views.delete, name='delete'),
    url(r'^blog$', views.blog, name='blog'),  
    url(r'^ABOUT$', views.ABOUT, name='ABOUT'),  
    url(r'^info$', views.info, name='info'),  
    url(r'^summer$', views.summer, name='summer'), 
    url(r'^next2$', views.next2, name='next2'),
    url(r'^adminbook$', views.adminbook, name='adminbook'),  
    url(r'^aadmin$', views.aadmin, name='aadmin'),  
    url(r'^aaccount$', views.aaccount, name='aaccount'),  
    url(r'^home_log$', views.home_log, name='home_log'),  
    url(r'^location$', views.view_location, name='view_location'),
    url(r'^add_location$', views.add_location, name='add_location'),
    url(r'^register$', views.register, name='register'),      
    url(r'^(\d+)/next/bookview$', views.bookview, name='bookview'),
    url(r'^(\d+)/bookstatus$', views.bookstatus, name='bookstatus'),  
    url(r'^(\d+)/bookstatus/statusupdate$', views.statusupdate, name='statusupdate'), 
    #url(r'^index$', views.index, name='index'),
]  

ownlist/models.py
from django.db import models


class Visitor(models.Model):
    vname = models.TextField(default='')
    vage = models.TextField(default='')
    vcnumber = models.TextField(default='') 
    vemail = models.TextField(default='')
    vusername = models.TextField(default='') 
    vpassword = models.TextField(default='')

class Booking(models.Model):
    blocation = models.TextField(default='')
    bdate = models.TextField(default='')    
    bdate2 = models.TextField(default='')     
    bpeople = models.TextField(default='')
    brates = models.TextField(default='')
    bstatus = models.TextField(default='')
    visitor = models.ForeignKey(Visitor, default=None, on_delete=models.CASCADE)

class Location(models.Model):
    llocation = models.TextField(default='')
    laddress = models.TextField(default='')

class Areg(models.Model):
    ausername = models.TextField(default='')
    apassword = models.TextField(default='')
  
class Member(models.Model):
    firstname=models.CharField(max_length=30)
    lastname=models.CharField(max_length=30)
    username=models.CharField(max_length=30)
    password=models.CharField(max_length=12)
 
    def __str__(self):
        return self.firstname + " " + self.lastname
   
 
'''

class CATEGORY(models.Model):
    ecategory = models.TextField(default='')
    eplaces = models.TextField(default='')
    eaddress = models.TextField(default='')
    
    personal_information = models.ForeignKey(PERSONAL_INFORMATION, default="", on_delete = models.CASCADE)


class TRAVEL_DETAILS(models.Model):
    etravelTips = models.TextField(default='')
    etraveldetails = models.TextField(default='')
    category = models.ForeignKey(CATEGORY, default="", on_delete = models.CASCADE)

class REVIEWS(models.Model):
    ereviews = models.TextField(default='')
    edate = models.TextField(default='')
    eexpenses = models.TextField(default='')
    travel_details = models.ForeignKey(TRAVEL_DETAILS, default="", on_delete = models.CASCADE)

class STATUS(models.Model):
    ecomments = models.TextField(default='') 
    efeedback = models.TextField(default='') 
    reviews = models.ForeignKey(REVIEWS, default="", on_delete = models.CASCADE)
'''

ownlist/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse  
from ownlist.models import Visitor, Booking, Location , Areg, Member


def home_page(request):
    return render(request, 'homepage.html')
def home_log(request): 
 if request.method == 'POST':
        if Visitor.objects.filter(vusername=request.POST['vvusername'], vpassword=request.POST['vvpassword']).exists():
            visitor_ = Visitor.objects.get(vusername=request.POST['vvusername'], vpassword=request.POST['vvpassword'])
            return redirect(f'{visitor_.id}/next')

        else:
            context = {'msg': 'Invalid username or password'}
            return render(request, 'homepage.html', context)

def new_list(request):                                                            
    svisitor = Visitor.objects.create(vname=request.POST['vvname'],vage=request.POST['vvage'],vcnumber=request.POST['vvcnumber'],vemail=request.POST['vvemail'],vusername=request.POST['vvusername'],vpassword=request.POST['vvpassword'])
    return redirect(f'{svisitor.id}/next')

def view_list(request, visitor_id):
    locations = Location.objects.all()
    visitor_ = Visitor.objects.get(id=visitor_id)
    return render(request, 'abooking.html', {'visitor': visitor_,'location' :  locations
})

def add_item(request, visitor_id):
    visitor_ = Visitor.objects.get(id=visitor_id)						
  
    Booking.objects.create(blocation=request.POST['bblocation'],bdate=request.POST['bbdate'],bdate2=request.POST['bbdate2'],bpeople=request.POST['bbpeople'],brates=request.POST['bbrates'],visitor=visitor_)
    return redirect(f'/{visitor_.id}/next')
def summer(request):
    return render(request, '3-4.html')
def ABOUT(request):
    return render(request, 'ABOUT.html')
def blog(request):
    return render(request, 'blog.html')
def info(request):
    return render(request, 'info.html')
def next2(request):
    return render(request, '5model .html')
def aadmin(request):
    return render(request, 'admin.html')
def bookstatus(request, visitor_id):
    locations = Location.objects.all()
    visitor_ = Visitor.objects.get(id=visitor_id)
    return render(request, 'bookstatus.html', {'visitor': visitor_,'location' :  locations
})
def statusupdate(request, visitor_id):
    visitor = Booking.objects.get(id=visitor_id)
    visitor.bstatus= request.POST['bbstatus']
    visitor.save()   
    return redirect(f'/{visitor.id}/bookstatus')
def register(request):
    visitors = Visitor.objects.all()
    return render(request, 'register.html', {'visitors' : visitors})
 
def bookview(request, visitor_id):
    locations = Location.objects.all()
    visitor_ = Visitor.objects.get(id=visitor_id)
    return render(request, 'bookview.html', {'visitor': visitor_,'location' :  locations
})


def aaccount(request):
    aregs = Aregs.objects.all()
    return render(request, 'account.html', {'aregs' : aregs})



def adminbook(request):
    visitors = Visitor.objects.all()
    return render(request, 'adminbooklist.html', {'visitors' : visitors})
def add_location(request):   
   locations = Location(llocation=request.POST['lllocation'],laddress=request.POST['lladdress'])
   locations.save()
   
   return redirect('/location')

def view_location(request):
    locations = Location.objects.all()
    return render(request, 'LocationReg.html', {'location' : locations})  








def edit(request, id):
    visitors = Visitor.objects.get(id=id)
    context = {'visitors': visitors}
    return render(request, 'edit.html', context)
 
def update(request, id):
    visitor = Visitor.objects.get(id=id)
    visitor.vname = request.POST['vvname']
    visitor.vage = request.POST['vvage']
    visitor.vcnumber = request.POST['vvcnumber']
    visitor.vusername = request.POST['vvusername']
    visitor.vpassword = request.POST['vvpassword']
    visitor.save()
    return redirect('/')
def delete(request, id):
    visitor = Visitor.objects.get(id=id)
    visitor.delete()
    return redirect('/')     
# Create your views here.
def index(request):
    if request.method == 'POST':
        member = Member(username=request.POST['username'], password=request.POST['password'],  firstname=request.POST['firstname'], lastname=request.POST['lastname'])
        member.save()
        return redirect('/')
    else:
        return render(request, 'index.html')
 

ownlist/templates/ABOUT.html
<!DOCTYPE html
<html>
<head>
<body style="background-image:url('https://littleletterslinked.com/wp-content/uploads/2020/07/HOTEL.jpg'); 
background-attachment: fixed; background-repeat: no-repeat;background-size: 100% 100%">
</body> 
<br>
<br>
<br>
  <h1>ABOUT</h1>
<center>

  <h2>FIND YOUR NEXT ESCAPE</h2><center/>
<h3>MISSION</h3>
<h4>VISSION</h4>
<style>
h1{
color:WHITE;
font-size: 50px; 
position: absolute;
left: 130px;
top: 5px;
  text-shadow: 2px 2px navy;

}

h2{
color:black;
font-size: 40px; 
position: absolute;
left: 450\px;
top: 70px;
font-family: 'Potta One', cursive;
  text-shadow: 2px 2px navy;
}

h3{
color:black;
font-size: 40px; 
position: absolute;
left: 600\px;
  text-shadow: 2px 2px navy;
top: 250px;
}
h4{
color:black;
font-size: 40px; 
position: absolute;
left: 600\px;
top: 400px;
  text-shadow: 2px 2px navy;
}


div.a {
  color: white;
font-size: 20px; 
font-text: bold;
position: absolute;
left: 20px;
top: 160px;
  text-shadow: 2px 2px black;
}
div.b {
 color: white;
font-size: 20px; 
font-text: bold;
position: absolute;
left: 230px;
top: 200px;

}
div.c {
 color: white;
font-size: 20px; 
font-text: bold;
position: absolute;
left: 20px;
top: 150px;
}
</style>
<body>
<center>
<div class="a">
<p> Having trouble finding an ideal places? AwareWeGo helps you find the best option that suits your taste. With just a click, you can instantlyfind your"nextescape".What are you waiting for? click and we're good to go!</p>
<div/>
<div class="b">
<p>We strive to give our clients the best available option with the utmost convenience in terms of traveling.</p>
<div/>
<div class="c">
<p>To be the most client-centric site, where people can find and discover places they might want to go in.</p>
<div/>
</body>
<center/>

</html>

ownlist/templates/abooking.html
<!DOCTYPE html>
<html>
<head>
    <title>Booking</title>
<body style="background-image:url('https://live.staticflickr.com/446/18667295963_31d3b50d16_b.jpg'); 
background-attachment: fixed; background-repeat: no-repeat;background-size: 100% 100%">
</body> 
<br>
<br>
<br>




<body>
<center>

<h1>Booking</h1>
</center>
<div>
<form method="POST" action="/{{visitor.id}}/add_item">

  <label for="bblocation">Location:</label><br>
 {% for location in location %}
<select id="bblocation" name="bblocation">
<option value="0">Add Location</option>
<option value="{{ location.llocation }}">{{ location.llocation }}</option>
  </select><br><br>
{% endfor %}
  <label for="bbdate">Check-in:</label><br>
  <input type="date" id="bbdate" name="bbdate" placeholder ="">  
  <label for="bbdate">Check-out:</label><br>
  <input type="date" id="bbdate2" name="bbdate2" placeholder ="">
 

<br><br>
  

  <label for="bbpeople">Pax:</label><br>
  <select id="bbpeople" name="bbpeople" onchange="cclass();">
		        <option value="">Select Pax</option>
  			<option value="1,000">1</option>
  			<option value="3,000">2-3</option>
  			<option value="6,000">4-5</option>
			</select><br><br>
<label for="bbrates">Rates:</label><br>
<input type="text4" id="bbrates" name="bbrates" placeholder="Amount"><br><br>

  <input type="submit" id="bbook" name="bbook" style="font-size: 16px;" value="Book"><br>
{% csrf_token %}


</div>
</form> 
	<script>
function cclass()
{
	var d=document.getElementById("bbpeople");
	var displaytext=d.options[d.selectedIndex].value;
	document.getElementById("bbrates").value=displaytext;
}




</script>
<table id="JudrieTable" name='tr'>
    <tr>
    <th>Location</th>
    <th>Check-in</th>
    <th>Check-out</th>
    <th>Pax</th>
    <th>Rates</th>
    <th>Action</th>
    </tr>
          
       <tr>
        {% for booking in visitor.booking_set.all %}
         <! -- {{ forloop.counter }}:  -->
        
        <td>{{ booking.blocation }}</td>
        <td>{{ booking.bdate}}</td>
 	<td>{{ booking.bdate2}}</td>
        <td>{{ booking.bpeople}}</td>
        <td>{{ booking.brates}}</td>
        <td>><a href="/{{visitor.id}}/next/bookview">status</a</td>
      
    
          </tr>
        {% endfor %}
    </table>
</tr>

</body>

<style>

input[type=text4], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  font-family: Copperplate, serif;
  font-size: 20px;
}

input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  font-family: Copperplate, serif;
  font-size: 20px;
}

input[type=date] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  font-family: Copperplate, serif;
  font-size: 20px;
}

input[type=submit] {
  width: 100%;
  background-color:#008d96;
  color: black;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-family: Lucida Handwriting, serif;
  font-size: 7px;

}

input[type=submit]:hover {
  background-color: #008B8B;


}

div {
  border-radius: 5px;
  background-color: rgba(1, 91, 97, 0.4);
  padding: 20px;
}

h1 {
  font-family: Lucida Handwriting, serif;
  font-size: 60px;
}
label {
  font-family: Lucida Handwriting, serif;
  font-size: 30px;
}
table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  text-align: center;
  padding: 8px;
  width: 100%;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
  background-color: #008B8B;
  color: black;
  width: 100%;
   font-family: Lucida Handwriting, serif;
  font-size: 20px;
}
</style>
</html>

ownlist/templates/base.html
//templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Python Django - Simple Registration & Login Form</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    </head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <a class="navbar-brand" href="https://tutorial101.blogspot.com">Cairocoders</a>
        </div>
    </nav>
    <div class="col-md-3"></div>
    <div class="col-md-6 well">
        <h3 class="text-primary">Python Django - Simple Registration & Login Form</h3>
        <hr style="border-top:1px dotted #000;"/>
        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

ownlist/templates/bookstatus.html
<!DOCTYPE html>
<html>
<head>
    <title>Booking</title>



<header>
    <h2><a href="/info"><i class="ion-plane"></i> AwareWeGo</a></h2>
    <nav>
      <ul>
       
        <li>
          <a href="/location" title="Register Location">Register Location</a>
        </li>

        <li>
          <a href="/blog" title="Blog">Blog</a>
        </li>
 
 	<li>
          <a href="/ABOUT" title="About">About</a>
        </li>
      </ul>
    </nav>
  </header>
<head>


<body style="background-image:url('https://assets2.rappler.com/02715D430B424A9AA0885F73B1BD259C/img/81D7119EAD014184BC71AB7985197F2A/2018_PH_bucket_list-January-07-2017-01.jpg'); 
background-attachment: fixed; background-repeat: no-repeat;background-size: 100% 100%">

<center>

<h1>Booking</h1>
</center>
<div>
<form method="POST" action="/{{visitor.id}}/bookstatus/statusupdate">



<table id="JudrieTable" name='tr'>
    <tr>
    <th>Location</th>
    <th>Check-in</th>
    <th>Check-out</th>
    <th>Pax</th>
    <th>Rates</th>
    <th>Status</th>
    </tr>
          
       <tr>
        {% for booking in visitor.booking_set.all %}
         <! -- {{ forloop.counter }}:  -->
        
        <td>{{ booking.blocation }}</td>
        <td>{{ booking.bdate}}</td>
 	<td>{{ booking.bdate2}}</td>
        <td>{{ booking.bpeople}}</td>
        <td>{{ booking.brates}}</td>
        <td><select id="bbstatus" name="bbstatus" onchange="cclass();">
		        <option value="">Select Status</option>
  			<option value="Approved">Approved</option>
  			<option value="Disapproved">Disapproved</option>
			</select><br><br></td>
      
    
          </tr>
        {% endfor %}
    </table>
</tr>
 

      
  <input type="submit" id="bsumbit" name="bsubmit" style="font-size: 16px;" value="Submit"><br>
{% csrf_token %}


</div>
</form> 

</body>

<style>


@import url('https://fonts.googleapis.com/css?family=Lato:400,700');

*, *:before, *:after {
  -webkit-box-sizing: inherit;
  -moz-box-sizing: inherit;
  box-sizing: inherit;
}

::-webkit-input-placeholder {
  color: #56585b;
}

::-moz-placeholder {
  color: #56585b;
}

:-moz-placeholder {
  color: #56585b;
}

html {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}

body {
  font-family: 'Lato', sans-serif;
  margin: 0;
  color: #0a0a0b;
}

ul, nav{
  list-style: none;
  padding: 0;
}

a {
  color: black;
  text-decoration: none;
  cursor: pointer;
  opacity: 0.9;
}

a:hover {
  opacity: 1;
}

h4 {
  font-size: 3rem;
  font-weight: 400;
  color: black;
  margin:2rem;
  font-family: Lucida Handwriting, serif;
}
i {
  font-size: 1rem;
}

header {
  position: absolute;
  top: 0;
  left: 0;
  z-index: 10;
  width: 100%;
  display: flex;
  justify-content: space-between;
  align-items: center;
  color: black;
  padding: 5px 50px 0;
  font-family: Lucida Handwriting, serif;
}

header nav ul {
  display: flex;
}

header nav li{
  margin: 0 15px;
}

header nav li:first-child{
  margin-left: 0; 
}

header nav li:last-child{
  margin-right: 0;  
}

a.btn {
  color: #fff;
  padding: 10px;
  border: 1px solid rgba(255,255,255,0.5);
  -webkit-transition: all 0.2s;
  -moz-transition: all 0.2s;
  transition: all 0.2s;
}

a.btn:hover {
  background: #d73851;
  border: 1px solid #d73851;
  color: #fff;
}

.cover  {
  height: 100vh;
  width: 100%;
  background: -webkit-gradient(linear, left top, left bottom, from(rgba(0,0,0,0.05)), to(rgba(0,0,0,0)));
  background: -webkit-linear-gradient(top, rgba(0,0,0,0.05) 0%, rgba(0,0,0,0) 100%);
  background: linear-gradient(to bottom, rgba(0,0,0,0.05) 0%, rgba(0,0,0,0) 100%);
  padding: 20px 50px;
  display: -webkit-box;
  display: flex;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  flex-direction: column;
  -webkit-box-pack: center;
  justify-content: center;
  -webkit-box-align: center;
  align-items: center;
}

.flex-form input[type="submit"] {
  background: #ef3f5a;
  border: 1px solid #ef3f5a;
  color: #fff;
  padding: 0 30px;
  cursor: pointer;
  -webkit-transition: all 0.2s;
  -moz-transition: all 0.2s;
  transition: all 0.2s;
}

.flex-form input[type="submit"]:hover {
  background: #d73851;
  border: 1px solid #d73851;
}

.flex-form {
  display: -webkit-box;
  display: flex;
  z-index: 10;
  position: relative;
  width: 500px;
  box-shadow: 4px 8px 16px rgba(0, 0, 0, 0.3);
}

.flex-form > * {
  border: 0;
  padding: 0 0 0 10px;
  background: #fff;
  line-height: 50px;
  font-size: 1rem;
  border-radius: 0;
  outline: 0;
  -webkit-appearance: none;
}


@media all and (max-width:800px) {
  body {
    font-size: 0.9rem;
  }

  .flex-form {
    width: 100%;
  }

  .flex-form > * {
    font-size: 0.9rem;
  }

  header {
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    flex-direction: column;
    padding: 10px !important;
  }

  header h2 {
    margin-bottom: 15px;
  }

  h1 {
    font-size: 2rem;
  }

  .cover {
    padding: 20px;
  }

  #madeby {
    padding: 30px 20px;
  }
}

@media all and (max-width:360px) {
  header nav li{
    margin: 0 10px;
  }

  .flex-form {
    display: -webkit-box;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    flex-direction: column;
  }

}




input[type=text4], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  font-family: Copperplate, serif;
  font-size: 20px;
}

input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  font-family: Copperplate, serif;
  font-size: 20px;
}

input[type=date] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  font-family: Copperplate, serif;
  font-size: 20px;
}

input[type=submit] {
  width: 100%;
  background-color:#008d96;
  color: black;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-family: Lucida Handwriting, serif;
  font-size: 7px;

}

input[type=submit]:hover {
  background-color: #008B8B;


}

div {
  border-radius: 5px;
  background-color: rgba(1, 91, 97, 0.4);
  padding: 20px;
}

h1 {
  font-family: Lucida Handwriting, serif;
  font-size: 60px;
}
label {
  font-family: Lucida Handwriting, serif;
  font-size: 30px;
}

p{
 font-family: Lucida Handwriting, serif;

  color: #000018;
  font-size: 25px;  
  padding: 14px 10px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  width:100%
}

a {
  color: blue;
}

a:hover {
  color: green;
}

table, td, th {
  border: 1px solid black;
}

table {
  width: 100%;
  border-collapse: collapse;
}
tr:nth-child(even){background-color: #f2f2f2}

th {
  background-color: #008B8B;
  color: black;
  
   font-family: Lucida Handwriting, serif;
  font-size: 20px;
}
</style> 

</html>

ownlist/templates/bookview.html
<!DOCTYPE html>
<html>
<head>
    <title>Booking</title>
<body style="background-image:url('https://assets2.rappler.com/02715D430B424A9AA0885F73B1BD259C/img/81D7119EAD014184BC71AB7985197F2A/2018_PH_bucket_list-January-07-2017-01.jpg'); 
background-attachment: fixed; background-repeat: no-repeat;background-size: 100% 100%">
</body> 
<br>
<br>
<br>




<body>
<center>

<h1>Booking</h1>
</center>
<div>
<form method="POST" action=" ">



<table id="JudrieTable" name='tr'>
    <tr>
    <th>Location</th>
    <th>Check-in</th>
    <th>Check-out</th>
    <th>Pax</th>
    <th>Rates</th>
    <th>Status</th>
    </tr>
          
       <tr>
        {% for booking in visitor.booking_set.all %}
         <! -- {{ forloop.counter }}:  -->
        
        <td>{{ booking.blocation }}</td>
        <td>{{ booking.bdate}}</td>
 	<td>{{ booking.bdate2}}</td>
        <td>{{ booking.bpeople}}</td>
        <td>{{ booking.brates}}</td>
        <td>{{ booking.bstatus}}</td>
  
    
          </tr>
        {% endfor %}
    </table>
</tr>
 

      
  <input type="submit" id="bsumbit" name="bsubmit" style="font-size: 16px;" value="Submit"><br>
{% csrf_token %}


</div>
</form> 

</body>

<style>

input[type=text4], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  font-family: Copperplate, serif;
  font-size: 20px;
}

input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  font-family: Copperplate, serif;
  font-size: 20px;
}

input[type=date] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  font-family: Copperplate, serif;
  font-size: 20px;
}

input[type=submit] {
  width: 100%;
  background-color:#008d96;
  color: black;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-family: Lucida Handwriting, serif;
  font-size: 7px;

}

input[type=submit]:hover {
  background-color: #008B8B;


}

div {
  border-radius: 5px;
  background-color: rgba(1, 91, 97, 0.4);
  padding: 20px;
}

h1 {
  font-family: Lucida Handwriting, serif;
  font-size: 60px;
}
label {
  font-family: Lucida Handwriting, serif;
  font-size: 30px;
}
table, td, th {
  border: 1px solid black;
}

table {
  width: 100%;
  border-collapse: collapse;
}
tr:nth-child(even){background-color: #f2f2f2}

th {
  background-color: #008B8B;
  color: black;
  
   font-family: Lucida Handwriting, serif;
  font-size: 20px;
}
</style>
</html>

ownlist/templates/index.html
//templates/index.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    <div class="col-md-2">
        <a href="/login">Login</a>
    </div>
    <div class="col-md-8">
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="username" class="form-control" required="required">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="password" class="form-control" required="required"/>
        </div>
        <div class="form-group">
            <label for="firstname">Firstname</label>
            <input type="text" name="firstname" class="form-control" required="required"/>
        </div>
        <div class="form-group">
            <label for="lastname">Lastname</label>
            <input type="text" name="lastname" class="form-control" required="required"/>
        </div>
        <br />
        <div class="form-group">
            <button type="submit" class="btn btn-primary form-control"><span class="glyphicon glyphicon-save"></span> Submit</button>
        </div>
    </div>
</form>
{% endblock %}